In [40]:
import pandas as pd
import numpy as np

In [41]:
edges = pd.read_csv('./graphs/CA-GrQc.txt', sep="\t", skiprows=range(0, 4), header=None)
#nodes = pd.read_csv('./graphs_processed/CA-GrQc.txt', sep=" ", header=1)
nodes = np.loadtxt('./graphs_processed/CA-GrQc.txt')

In [29]:
edges

           0      1
0       3466    937
1       3466   5233
2       3466   8579
3       3466  10310
4       3466  15931
5       3466  17038
6       3466  18720
7       3466  19607
8      10310   1854
9      10310   3466
10     10310   4583
11     10310   5233
12     10310   9572
13     10310  10841
14     10310  13056
15     10310  14982
16     10310  16310
17     10310  19640
18     10310  23855
19     10310  24372
20     10310  24814
21      5052    899
22      5052   1796
23      5052   2287
24      5052   3096
25      5052   3386
26      5052   4472
27      5052   5346
28      5052   5740
29      5052   6094
...      ...    ...
28950  21848  16231
28951  21848  16590
28952  21848  16730
28953  21848  19957
28954  21848  22320
28955  21848  22423
28956  22320    832
28957  22320   3387
28958  22320   4703
28959  22320   7447
28960  22320   9764
28961  22320  10117
28962  22320  14340
28963  22320  14370
28964  22320  15006
28965  22320  16231
28966  22320  16590
28967  22320  16730
28968  22320  19957
28969  22320  21848
28970  22320  22423
28971   5774  10432
28972   4836   9593
28973  17464    320
28974  17464  15108
28975  10154   9224
28976  10154  16830
28977  11113  21723
28978  11113  23836
28979  11113  25050

[28980 rows x 2 columns]